name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          version: 18.x
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Install eslint-plugin-n
        run: yarn add eslint-plugin-n
      - name: Run lint
        run: npx eslint .
