name: Test

on: [push, pull_request]

env:
  NODE_OPTIONS: --experimental-vm-modules

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Test
      run: |
        npm install
        npm ci
        run test

